/**
 * 七段位矩阵夹具（卡 #33：看板列 / 列表视图）——独立成文件：boardTestFixture 已到 max-lines 上限。
 *
 * 形态真源同一份：`board.golden.json`（字段名、嵌套、stage/statusRule/attention 写法逐项对齐）。
 * 与 `GOLDEN_SHAPED_BOARD` 分开是刻意的：本夹具要**七段位全覆盖**（含 golden 也有的阻塞特性、
 * 已取消卡），而既有夹具的形态已被 #32 的守卫钉住，不搅动。
 *
 * 卡 #34 补两处 `assignees`（v2.1 形态：卡 #8 标准管线、卡 #13 非标准管线 debugger → test-verifier），
 * 供表格 assignees 列与弹窗的映射断言——只新增字段，不动 #33 已钉住的形态。
 *
 * 列分配期望（测试里逐条写死，独立于实现）：
 * 待设计 = 2 个 plan 安排类 + 2 个 interview-only（聚合）；待办 = #7/#10/#14；
 * 执行中 = 特性 1 + #8；审核中 = #13；阻塞 = 特性 2；已完成 = #9；已取消 = #12。
 * #14 段位=待办但带 `unmerged-worktree` 且 updatedAt 最老 —— 专钉「attention 置顶」。
 */
import { WORKSPACE } from "./boardTestFixture.js";

export const STAGE_MATRIX_BOARD = {
  version: 2,
  project: { root: WORKSPACE, name: "ZCode" },
  updatedAt: "2026-10-09T16:05:00+08:00",
  generatedBy: "zcode-board/0.2",
  features: [
    {
      id: "spec:preview-channel",
      no: 1,
      label: "1",
      kind: "spec",
      title: "预览通道（Preview Channel）",
      status: "active",
      statusRule: "progress.stages.design=active",
      stage: "执行中",
      attention: [],
      progress: { totalTasks: 4, completedTasks: 1 },
      updatedAt: "2026-10-09T15:30:00+08:00",
      tasks: [
        {
          no: 7,
          label: "1.1",
          title: "预览发布通道（workflow）",
          status: "pending",
          statusRule: "tasks.md checkbox unchecked",
          stage: "待办",
          draft: false,
          attention: [],
          blockers: [{ kind: "external", summary: "dev 污染 atom feed 待验证", evidence: [] }],
          lastRun: {
            at: "2026-10-09T14:05:00+08:00",
            role: "code-reviewer",
            result: "done",
            stoppedAt: null,
            next: null,
          },
          activeRun: null,
          worktree: null,
          updatedAt: "2026-10-09T14:05:00+08:00",
        },
        {
          no: 8,
          label: "1.2",
          title: "让开关立刻生效（核心）",
          status: "active",
          statusRule: "activeRun.role=implementer（干活角色）",
          stage: "执行中",
          draft: false,
          attention: ["interrupted-resume", "unmerged-worktree"],
          blockers: [],
          lastRun: {
            at: "2026-10-09T14:20:00+08:00",
            role: "implementer",
            result: "partial",
            stoppedAt: 8,
            next: "补 updater 单测后重新验证",
          },
          assignees: ["implementer", "test-verifier", "code-reviewer", "integrator"],
          activeRun: { role: "implementer", at: "2026-10-09T14:20:00+08:00" },
          worktree: ".zcode/worktrees/task-8",
          updatedAt: "2026-10-09T14:20:00+08:00",
        },
        {
          no: 9,
          label: "1.3",
          title: "通道可见 + 版本序语义",
          status: "completed",
          statusRule: "tasks.md checkbox checked",
          stage: "已完成",
          draft: false,
          attention: [],
          blockers: [],
          lastRun: {
            at: "2026-10-09T15:30:00+08:00",
            role: "integrator",
            result: "done",
            stoppedAt: null,
            next: null,
          },
          activeRun: null,
          worktree: null,
          updatedAt: "2026-10-09T15:30:00+08:00",
        },
      ],
    },
    {
      id: "spec:payment-split",
      no: 2,
      label: "2",
      kind: "spec",
      title: "支付拆分",
      status: "blocked",
      statusRule: "progress.stages.implementation=blocked",
      stage: "阻塞",
      attention: [],
      progress: { totalTasks: 2, completedTasks: 0 },
      updatedAt: "2026-10-09T09:00:00+08:00",
      tasks: [
        {
          no: 10,
          label: "2.1",
          title: "拆出支付回调服务",
          status: "pending",
          statusRule: "tasks.md checkbox unchecked",
          stage: "待办",
          draft: false,
          attention: [],
          blockers: [{ kind: "external", summary: "回调幂等键待上游定", evidence: [] }],
          lastRun: null,
          activeRun: null,
          worktree: null,
          updatedAt: "2026-10-09T09:00:00+08:00",
        },
      ],
    },
    {
      id: "plan:sess_f1a2d0bb",
      no: 6,
      label: "6",
      kind: "plan",
      title: "会话按需加载：上拖后台加载时，当前可见内容不许位移",
      status: "pending",
      statusRule: "plan 无勾选记录且无执行证据",
      stage: "待设计",
      attention: ["arranged-not-expanded"],
      progress: null,
      updatedAt: "2026-10-01T10:42:00+08:00",
      tasks: [],
    },
    {
      id: "plan:sess_1f3c5d7e",
      no: 11,
      label: "11",
      kind: "plan",
      title: "取消与审核态样例",
      status: "pending",
      statusRule: "plan 无勾选记录且无执行证据",
      stage: "待设计",
      attention: ["arranged-not-expanded"],
      progress: null,
      updatedAt: "2026-10-09T13:10:00+08:00",
      tasks: [
        {
          no: 12,
          label: "11.1",
          title: "上游方案作废的旧卡",
          status: "cancelled",
          statusRule: "cancelled: 上游方案作废（取消留痕、号不复用）",
          stage: "已取消",
          draft: false,
          attention: [],
          blockers: [],
          lastRun: {
            at: "2026-10-09T08:00:00+08:00",
            role: "implementer",
            result: "interrupted",
            stoppedAt: 12,
            next: null,
          },
          activeRun: null,
          worktree: null,
          updatedAt: "2026-10-09T08:00:00+08:00",
        },
        {
          no: 13,
          label: "11.2",
          title: "等判定的卡",
          status: "pending",
          statusRule: "activeRun.role=test-verifier（判断角色）",
          stage: "审核中",
          draft: false,
          attention: ["interrupted-resume"],
          blockers: [],
          lastRun: {
            at: "2026-10-09T13:10:00+08:00",
            role: "test-verifier",
            result: "partial",
            stoppedAt: 13,
            next: "复核缺口清单",
          },
          assignees: ["debugger", "test-verifier"],
          activeRun: { role: "test-verifier", at: "2026-10-09T13:10:00+08:00" },
          worktree: null,
          updatedAt: "2026-10-09T13:10:00+08:00",
        },
        {
          no: 14,
          label: "11.3",
          title: "现场未回流的老卡",
          status: "pending",
          statusRule: "tasks.md checkbox unchecked",
          stage: "待办",
          draft: false,
          attention: ["unmerged-worktree"],
          blockers: [],
          lastRun: {
            at: "2026-10-09T08:00:00+08:00",
            role: "implementer",
            result: "done",
            stoppedAt: null,
            next: null,
          },
          activeRun: null,
          worktree: ".zcode/worktrees/task-14",
          updatedAt: "2026-10-09T08:00:00+08:00",
        },
      ],
    },
    {
      id: "interview:itw-a",
      kind: "interview-only",
      title: "面板分组与过滤",
      status: "pending",
      statusRule: "interview.status=open 且 outcome=none（无产物）",
      stage: "待设计",
      attention: ["interviewed-not-arranged"],
      updatedAt: "2026-10-09T10:00:00+08:00",
      tasks: [],
    },
    {
      id: "interview:itw-b",
      kind: "interview-only",
      title: "远端设备投影（尚未落卡）",
      status: "pending",
      statusRule: "interview.status=open 且 outcome=none（无产物）",
      stage: "待设计",
      attention: ["interviewed-not-arranged"],
      updatedAt: "2026-10-09T11:00:00+08:00",
      tasks: [],
    },
  ],
  attentionSummary: {
    interviewedNotArranged: 2,
    arrangedNotExpanded: 2,
    interruptedResume: 2,
    unmergedWorktree: 2,
  },
  diagnostics: [],
};
